#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact 
    become: true
    get_url:
      url: http://3.235.108.228:8080/var/lib/jenkins/workspace/Demo_project/java-source/target/iwayQApp-2.0-RELEASE.war
      dest: /home/ec2-user
      url_username: sai
      url_password: password

  - name: Rename .war Artifact
    command: mv iwayQApp-2.0-RELEASE.war iwayq.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: iwayq
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: saikumar0803
     password: rams@0803

    
  - name: Push to docker hub
    docker_image:
      name: iwayq
      repository: iwayqdockertest/iwayq:1.0
      push: yes
      source: local