#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: copying .war artifact 
    copy:
      src: /home/jenkinsslave/workspace/Jenkins-Pipeline/java-source/target/iwayQApp-2.0-RELEASE.war
      dest: /home/ec2-user
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat
      source: pull

  - name: Build image and with build args
    docker_image:
      name: iwayq .
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  