#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
spec:
  selector:
     matchlabels:
        app: login-app
  replicas: 1
  strategy:
     type: RollingUpdate
     rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
  
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-container
        image: saikumar0803/bike
        imagePullPolicy: Always
        ports:
        - containerPort: 8080