#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: copying .war artifact 
    copy:
      src: /home/jenkinsslave/workspace/Jenkins-Pipeline/java-source/target/loginApp-2.0-RELEASE.war
      dest: /home/ec2-user

  - name: Rename .war Artifact
    command: mv loginApp-2.0-RELEASE.war login.war
  
  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image and with build args
    docker_image:
      name: login
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: saikumar0803
     password: rams@0803

    
  - name: Push to docker hub
    docker_image:
      name: login
      repository: saikumar0803/login:2.0
      push: yes
      source: local