#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
  labels:
    app: login-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-container
        image: saikumar0803/login:3.0
        ports:
        - containerPort: 8080