#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoq-deploy
  labels:
    app: demoq-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoq-app
  template:
    metadata:
      labels:
        app: demoq-app
    spec:
      containers:
      - name: demoq-container
        image: demoqdockertest/demoq:1.0
        ports:
        - containerPort: 8080