#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: copying .war artifact 
    copy:
      src: /home/jenkinsslave/workspace/Jenkins-Pipeline/java-source/target/iwayQApp-2.0-RELEASE.war
      dest: /home/ec2-user

  - name: Build image and with build args
    docker_image:
      name: blue
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
      username: saikumar0803
      password: rams@0803
    
  - name: Push to docker hub
    docker_image:
      name: blue
      repository: saikumar0803/blue
      push: yes
      source: local
  