#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
  labels:
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  strategy:
     type: RollingUpdate
     rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1  
  
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-container
        image: saikumar0803/bike:tagVersion
        imagePullPolicy : Always
        ports:
        - containerPort: 8080